[project]
name = "semantic_nerfacto"
version = "0.0.0"

dependencies = [
    "nerfstudio>=1.0.0"
]

[tool.setuptools.packages.find]
include = ["semantic_nerfacto*"]

[project.entry-points.'nerfstudio.method_configs']
semantic_nerfacto = 'semantic_nerfacto.semantic_nerfacto_config:semantic_nerfacto'
semantic_depth_nerfacto = 'semantic_nerfacto.semantic_nerfacto_config:semantic_depth_nerfacto'

# Custom dataparser causes circular import
# [project.entry-points.'nerfstudio.dataparser_configs']
# semantic_dataparser = 'semantic_nerfacto.semantic_nerfacto_config:semantic_dataparser'